# Site settings
title: Orbital Shell
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/orbital-shell/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; licence MIT 2021
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
